# frozen_string_literal: true
# Generated file, DO NOT EDIT!

ansible_mod = Ansible::Ruby::Modules

ansible_mod.autoload(:Ec2_ami_find, 'ansible/ruby/modules/generated/cloud/amazon/ec2_ami_find')
ansible_mod.autoload(:Ec2, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2')
ansible_mod.autoload(:Ec2_ami, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2_ami')
ansible_mod.autoload(:Ec2_asg, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2_asg')
ansible_mod.autoload(:Ec2_eip, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2_eip')
ansible_mod.autoload(:Ec2_group, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2_group')
ansible_mod.autoload(:Ec2_vol, 'ansible/ruby/modules/custom/cloud/core/amazon/ec2_vol')
ansible_mod.autoload(:Iam, 'ansible/ruby/modules/custom/cloud/core/amazon/iam')
ansible_mod.autoload(:Iam_policy, 'ansible/ruby/modules/custom/cloud/core/amazon/iam_policy')
ansible_mod.autoload(:Docker_container, 'ansible/ruby/modules/custom/cloud/core/docker/docker_container')
ansible_mod.autoload(:Command, 'ansible/ruby/modules/custom/commands/command')
ansible_mod.autoload(:Raw, 'ansible/ruby/modules/custom/commands/raw')
ansible_mod.autoload(:Script, 'ansible/ruby/modules/custom/commands/script')
ansible_mod.autoload(:Shell, 'ansible/ruby/modules/custom/commands/shell')
ansible_mod.autoload(:Copy, 'ansible/ruby/modules/custom/files/copy')
ansible_mod.autoload(:Fetch, 'ansible/ruby/modules/custom/files/fetch')
ansible_mod.autoload(:File, 'ansible/ruby/modules/custom/files/file')
ansible_mod.autoload(:Lineinfile, 'ansible/ruby/modules/custom/files/lineinfile')
ansible_mod.autoload(:Template, 'ansible/ruby/modules/custom/files/template')
ansible_mod.autoload(:Unarchive, 'ansible/ruby/modules/custom/files/unarchive')
ansible_mod.autoload(:Get_url, 'ansible/ruby/modules/custom/network/basics/get_url')
ansible_mod.autoload(:Gem, 'ansible/ruby/modules/custom/packaging/language/gem')
ansible_mod.autoload(:Firewalld, 'ansible/ruby/modules/custom/system/firewalld')
ansible_mod.autoload(:User, 'ansible/ruby/modules/custom/system/user')
ansible_mod.autoload(:Meta, 'ansible/ruby/modules/custom/utilities/helper/meta')
ansible_mod.autoload(:Include_vars, 'ansible/ruby/modules/custom/utilities/include_vars')
ansible_mod.autoload(:Pause, 'ansible/ruby/modules/custom/utilities/logic/pause')
ansible_mod.autoload(:Set_fact, 'ansible/ruby/modules/custom/utilities/logic/set_fact')
ansible_mod.autoload(:Wait_for, 'ansible/ruby/modules/custom/utilities/logic/wait_for')
