AllCops:
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'

# Not that big of a problem
Metrics/LineLength:
  Enabled: false

# $? rule didn't work
Style/SpecialGlobalVars:
  Enabled: false

Metrics/ModuleLength:
  Max: 200
  # Parsing is a hairy business
  Exclude:
    - 'util/parser/option.rb'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

# 15 seems a bit too noobish
Metrics/AbcSize:
  Max: 35

# 6 seems a bit low
Metrics/CyclomaticComplexity:
  Max: 8

# kind of pointless here
Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# if this is really high, fine but 5 is too small
Metrics/ParameterLists:
  Max: 8

Lint/UnifiedInteger:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/**/*'
    - Rakefile

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'lib/ansible/ruby/modules/all.rb'
