AllCops:
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'

# Not that big of a problem
Metrics/LineLength:
  Enabled: false

# $? rule didn't work
Style/SpecialGlobalVars:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

# 15 seems a bit too noobish
Metrics/AbcSize:
  Max: 35

# 6 seems a bit low
Metrics/CyclomaticComplexity:
  Max: 8

# kind of pointless here
Style/Documentation:
  Enabled: false

# don't want complains about filename/syntax
Style/FileName:
  Enabled: false

# if this is really high, fine but 5 is too small
Metrics/ParameterLists:
  Max: 8

Lint/UnifiedInteger:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/**/*'
    - Rakefile
