# frozen_string_literal: true

require 'ansible/ruby/rake/tasks'

desc 'named ansible task'
Ansible::Ruby::Rake::Execute.new do |task|
  task.playbooks = 'webservers.rb'
end

desc 'AMI test'
Ansible::Ruby::Rake::Execute.new :ami do |task|
  task.playbooks = 'image_copy.rb'
end

desc 'Command test'
Ansible::Ruby::Rake::Execute.new :command do |task|
  task.playbooks = 'command.rb'
end

desc 'Block test'
Ansible::Ruby::Rake::Execute.new :block do |task|
  task.playbooks = 'block.rb'
  task.options = '-e stuff=true'
end
